name = "remix-hono-turbo-web"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-04-16"
compatibility_flags = [ "nodejs_compat" ]
services = [
    { binding = "BACKEND", service = "remix-hono-turbo-backend" },
]

[build]
command = "pnpm run build:cloudflare"

[vars]
NODE_VERSION = "20"
NODE_ENV = "production"
